// Auto-generated by scripts/scan-music.mjs
// DO NOT EDIT MANUALLY
// Generated at: 2026-06-07T09:41:56.354Z
// Total tracks: 2

import type { MusicTrack } from "../types/config";

export const generatedPlaylist: MusicTrack[] = [
  {
    title: "JANE DOE",
    artist: "米津玄師",
    artistRaw: "米津玄師, 宇多田ヒカル",
    featuredArtists: ["宇多田ヒカル"],
    albumArtist: "米津玄師, 宇多田ヒカル",
    album: "JANE DOE",
    year: 2025,
    genre: "POP",
    tags: ["POP"],
    track: { no: 1, of: 1 },
    composer: "米津玄師",
    cover: "/assets/music/cover/001.JANE_DOE_cbf29372.jpg",
    url: "/assets/music/url/001.JANE%20DOE.flac",
    duration: 235,
    sampleRate: 48000,
    bitsPerSample: 24,
    channels: 2,
    bitrate: 1824550.5650994575,
    codec: "flac",
    codecName: "FLAC",
    qualityTier: "hiRes",
    qualityLabel: "Hi-Res 无损",
    qualityBadge: "HR"
  },
  {
    title: "AD ASTRA",
    artist: "STARSET",
    albumArtist: "STARSET",
    album: "SILOS",
    year: 2025,
    genre: "ROCK",
    tags: ["ROCK"],
    track: { no: 15, of: 16 },
    composer: "STARSET",
    cover: "/assets/music/cover/15.AD_ASTRA_5632a113.jpg",
    url: "/assets/music/url/15.AD%20ASTRA.flac",
    duration: 275,
    sampleRate: 48000,
    bitsPerSample: 24,
    channels: 2,
    bitrate: 1960569.8239409826,
    codec: "flac",
    codecName: "FLAC",
    qualityTier: "hiRes",
    qualityLabel: "Hi-Res 无损",
    qualityBadge: "HR"
  },
];
